from __future__ import annotations

from typing import Any, Protocol

from execution.events import MarketOrderEvent, MarketTradeEvent
from models import Market, Token


class TradeClient(Protocol):
    def create_buy_order(self, token: Token, shares: float, price: float) -> tuple[str, Any]: ...

    def create_sell_order(self, token: Token, shares: float, price: float) -> tuple[str, Any]: ...

    def submit_order(self, order: Any) -> bool: ...

    def get_cash_balance(self) -> float: ...

    def get_order_by_id(self, order_id: str) -> MarketOrderEvent | None: ...

    def get_trade_by_id(self, trade_id: str) -> MarketTradeEvent | None: ...

    def cancel_order_by_id(self, order_id: str) -> tuple[bool, str]: ...

    def calc_fee_amount(self, market: Market, shares: float, price: float) -> float: ...
